In [59]:
import pandas as pd

a=pd.read_csv("weatherAUS.csv")
a

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [60]:
a.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [61]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

In [62]:
a.keys()

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [63]:
a.duplicated().sum()

0

In [64]:
a.drop(columns=['Date', 'Location','WindGustDir'],inplace=True)

In [65]:
a

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,13.4,22.9,0.6,NaN,NaN,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,7.4,25.1,0.0,NaN,NaN,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,12.9,25.7,0.0,NaN,NaN,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,9.2,28.0,0.0,NaN,NaN,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,17.5,32.3,1.0,NaN,NaN,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2.8,23.4,0.0,NaN,NaN,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,3.6,25.3,0.0,NaN,NaN,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,5.4,26.9,0.0,NaN,NaN,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,7.8,27.0,0.0,NaN,NaN,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,14.9,NaN,0.0,NaN,NaN,NaN,ESE,ESE,17.0,17.0,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [66]:
flot_data=a.select_dtypes(include="float64")

from sklearn.impute import SimpleImputer

sim=SimpleImputer(strategy="mean")
# data=sim.fit_transform(flot_data)
for i in flot_data.keys():
    a[i]=sim.fit_transform(flot_data[[i]])

In [67]:
ob_data=a.select_dtypes(include="object")

from sklearn.impute import SimpleImputer
sim=SimpleImputer(strategy="most_frequent")

for i in ob_data.keys():
    a[[i]]=sim.fit_transform(ob_data[[i]])

In [68]:
a.isnull().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [69]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   MinTemp        145460 non-null  float64
 1   MaxTemp        145460 non-null  float64
 2   Rainfall       145460 non-null  float64
 3   Evaporation    145460 non-null  float64
 4   Sunshine       145460 non-null  float64
 5   WindGustSpeed  145460 non-null  float64
 6   WindDir9am     145460 non-null  object
 7   WindDir3pm     145460 non-null  object
 8   WindSpeed9am   145460 non-null  float64
 9   WindSpeed3pm   145460 non-null  float64
 10  Humidity9am    145460 non-null  float64
 11  Humidity3pm    145460 non-null  float64
 12  Pressure9am    145460 non-null  float64
 13  Pressure3pm    145460 non-null  float64
 14  Cloud9am       145460 non-null  float64
 15  Cloud3pm       145460 non-null  float64
 16  Temp9am        145460 non-null  float64
 17  Temp3pm        145460 non-null  float64
 18  RainToday      145460 non-null  object
 19  RainTomorrow   145460 non-null  object
dtypes: float64(16), object(4)
memory usage: 22.2+ MB

In [70]:
ob=a.select_dtypes(include="object")

from sklearn.preprocessing import LabelEncoder

la=LabelEncoder()

for i in ob.keys():
    a[i]=la.fit_transform(ob[[i]])

c:\Users\sinha\anaconda3\envs\ENV1\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\sinha\anaconda3\envs\ENV1\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\sinha\anaconda3\envs\ENV1\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\sinha\anaconda3\envs\ENV1\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [71]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   MinTemp        145460 non-null  float64
 1   MaxTemp        145460 non-null  float64
 2   Rainfall       145460 non-null  float64
 3   Evaporation    145460 non-null  float64
 4   Sunshine       145460 non-null  float64
 5   WindGustSpeed  145460 non-null  float64
 6   WindDir9am     145460 non-null  int32
 7   WindDir3pm     145460 non-null  int32
 8   WindSpeed9am   145460 non-null  float64
 9   WindSpeed3pm   145460 non-null  float64
 10  Humidity9am    145460 non-null  float64
 11  Humidity3pm    145460 non-null  float64
 12  Pressure9am    145460 non-null  float64
 13  Pressure3pm    145460 non-null  float64
 14  Cloud9am       145460 non-null  float64
 15  Cloud3pm       145460 non-null  float64
 16  Temp9am        145460 non-null  float64
 17  Temp3pm        145460 non-null  float64
 18  RainToday      145460 non-null  int32
 19  RainTomorrow   145460 non-null  int32
dtypes: float64(16), int32(4)
memory usage: 20.0 MB

In [72]:
x=a.iloc[:,:-3]

y=a.iloc[:,-2]
z=a.iloc[:,-1]

In [73]:
x

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am
0,13.4,22.900000,0.6,5.468232,7.611178,44.00000,13,14,20.0,24.0,71.0,22.0,1007.7,1007.1,8.000000,4.50993,16.9
1,7.4,25.100000,0.0,5.468232,7.611178,44.00000,6,15,4.0,22.0,44.0,25.0,1010.6,1007.8,4.447461,4.50993,17.2
2,12.9,25.700000,0.0,5.468232,7.611178,46.00000,13,15,19.0,26.0,38.0,30.0,1007.6,1008.7,4.447461,2.00000,21.0
3,9.2,28.000000,0.0,5.468232,7.611178,24.00000,9,0,11.0,9.0,45.0,16.0,1017.6,1012.8,4.447461,4.50993,18.1
4,17.5,32.300000,1.0,5.468232,7.611178,41.00000,1,7,7.0,20.0,82.0,33.0,1010.8,1006.0,7.000000,8.00000,17.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2.8,23.400000,0.0,5.468232,7.611178,31.00000,9,1,13.0,11.0,51.0,24.0,1024.6,1020.3,4.447461,4.50993,10.1
145456,3.6,25.300000,0.0,5.468232,7.611178,22.00000,9,3,13.0,9.0,56.0,21.0,1023.5,1019.1,4.447461,4.50993,10.9
145457,5.4,26.900000,0.0,5.468232,7.611178,37.00000,9,14,9.0,9.0,53.0,24.0,1021.0,1016.8,4.447461,4.50993,12.5
145458,7.8,27.000000,0.0,5.468232,7.611178,28.00000,10,3,13.0,7.0,51.0,24.0,1019.4,1016.5,3.000000,2.00000,15.1
145459,14.9,23.221348,0.0,5.468232,7.611178,40.03523,2,2,17.0,17.0,62.0,36.0,1020.2,1017.9,8.000000,8.00000,15.0

In [74]:
y.value_counts()

RainToday
0    113580
1     31880
Name: count, dtype: int64

In [75]:
z.value_counts()

RainTomorrow
0    113583
1     31877
Name: count, dtype: int64

In [76]:
yz=a.iloc[:,-2:]
yz

        RainToday  RainTomorrow
0               0             0
1               0             0
2               0             0
3               0             0
4               0             0
...           ...           ...
145455          0             0
145456          0             0
145457          0             0
145458          0             0
145459          0             0

[145460 rows x 2 columns]

In [77]:
from imblearn.over_sampling import RandomOverSampler

ros=RandomOverSampler()
x,z=ros.fit_resample(x,z)

In [79]:


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,z,random_state=42,test_size=0.2)

In [80]:
from sklearn.preprocessing import StandardScaler

st=StandardScaler()
x_train=st.fit_transform(x_train)
x_test=st.fit_transform(x_test)

In [83]:
from sklearn.tree import DecisionTreeClassifier

Dtc=DecisionTreeClassifier()
Dtc.fit(x_train,y_train)
Dtc.score(x_test,y_test)*100

90.93850420390017

In [87]:
y_pred=Dtc.predict(x_test)

In [103]:
from sklearn.ensemble import RandomForestClassifier

rfr=RandomForestClassifier(n_estimators=50,max_depth=50,criterion="entropy")
rfr.fit(x_train,y_train)
rfr.score(x_test,y_test)*100

94.46889994277413

In [104]:
t_pred=rfr.predict(x_test)

In [105]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,t_pred)

array([[20600,  1986],
       [  527, 22321]], dtype=int64)

In [106]:
confusion_matrix(y_test,y_pred)

array([[19127,  3459],
       [  658, 22190]], dtype=int64)